services:
  mongo:
    image: mongo:latest
    container_name: MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data/db:/data/db
    networks:
      - app_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${USERNAME}:${PASSWORD}@${MONGO_URL}:${MONGO_PORT}/ --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  data:
    build: ./Data-Insertion
    container_name: Data-Inserter
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: FastAPI_Backend
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - ${API_PORT}:${API_PORT}

networks:
  app_network:
    driver: bridge